### ISSUE TITLE
Github Action: if PR with tag 'cookiecutter' is merged, it will create an issue in cookiecutter-pypackage

### ISSUE THREAD

**Issue by ahms5** [pyfar/cookiecutter-pypackage#18]
apply changes from https://github.com/pyfar/pyfar/pull/586

**Comment by mberz** [comment]
this can be closed, right? :)

**Comment by ahms5** [comment]
not yet, we need to apply the change to the cookiecutter first

**Comment by mberz** [comment]
I know :)
